/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QuestionPaperRegistry } from './QuestionPaperRegistry.js';
export * as factories from './factories/index.js';
export { QuestionPaperRegistry__factory } from './factories/QuestionPaperRegistry__factory.js';