/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface QuestionPaperRegistryInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "centerPapers" | "originalPapers" | "storeCenterPaper" | "storeOriginalPaper"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CenterPaperStored" | "OriginalPaperStored"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'centerPapers', values: [string, string]): string;
encodeFunctionData(functionFragment: 'originalPapers', values: [string]): string;
encodeFunctionData(functionFragment: 'storeCenterPaper', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'storeOriginalPaper', values: [string]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'centerPapers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'originalPapers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeCenterPaper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeOriginalPaper', data: BytesLike): Result;
  }

  
    export namespace CenterPaperStoredEvent {
      export type InputTuple = [originalHash: string, centerId: string, watermarkedHash: string, timestamp: BigNumberish];
      export type OutputTuple = [originalHash: string, centerId: string, watermarkedHash: string, timestamp: bigint];
      export interface OutputObject {originalHash: string, centerId: string, watermarkedHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OriginalPaperStoredEvent {
      export type InputTuple = [originalHash: string, timestamp: BigNumberish];
      export type OutputTuple = [originalHash: string, timestamp: bigint];
      export interface OutputObject {originalHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface QuestionPaperRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): QuestionPaperRegistry;
    waitForDeployment(): Promise<this>;

    interface: QuestionPaperRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    centerPapers: TypedContractMethod<
      [arg0: string, arg1: string, ],
      [[string, string, bigint] & {centerId: string, watermarkedHash: string, timestamp: bigint }],
      'view'
    >
    

    
    originalPapers: TypedContractMethod<
      [arg0: string, ],
      [[string, bigint] & {originalHash: string, timestamp: bigint }],
      'view'
    >
    

    
    storeCenterPaper: TypedContractMethod<
      [_originalHash: string, _centerId: string, _watermarkedHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    storeOriginalPaper: TypedContractMethod<
      [_originalHash: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'centerPapers'): TypedContractMethod<
      [arg0: string, arg1: string, ],
      [[string, string, bigint] & {centerId: string, watermarkedHash: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'originalPapers'): TypedContractMethod<
      [arg0: string, ],
      [[string, bigint] & {originalHash: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'storeCenterPaper'): TypedContractMethod<
      [_originalHash: string, _centerId: string, _watermarkedHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'storeOriginalPaper'): TypedContractMethod<
      [_originalHash: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CenterPaperStored'): TypedContractEvent<CenterPaperStoredEvent.InputTuple, CenterPaperStoredEvent.OutputTuple, CenterPaperStoredEvent.OutputObject>;
getEvent(key: 'OriginalPaperStored'): TypedContractEvent<OriginalPaperStoredEvent.InputTuple, OriginalPaperStoredEvent.OutputTuple, OriginalPaperStoredEvent.OutputObject>;

    filters: {
      
      'CenterPaperStored(string,string,string,uint256)': TypedContractEvent<CenterPaperStoredEvent.InputTuple, CenterPaperStoredEvent.OutputTuple, CenterPaperStoredEvent.OutputObject>;
      CenterPaperStored: TypedContractEvent<CenterPaperStoredEvent.InputTuple, CenterPaperStoredEvent.OutputTuple, CenterPaperStoredEvent.OutputObject>;
    

      'OriginalPaperStored(string,uint256)': TypedContractEvent<OriginalPaperStoredEvent.InputTuple, OriginalPaperStoredEvent.OutputTuple, OriginalPaperStoredEvent.OutputObject>;
      OriginalPaperStored: TypedContractEvent<OriginalPaperStoredEvent.InputTuple, OriginalPaperStoredEvent.OutputTuple, OriginalPaperStoredEvent.OutputObject>;
    
    };
  }